// Generated by Skyramp v1.3.34 on 2026-07-15 00:21:40.996288098 +0000 UTC m=+458.575592983
// Command: skyramp generate integration rest \
// 		--auth-header Cookie \
// 		--framework playwright \
// 		--language typescript \
// 		--output availability_schedule_create_default_hours.spec.ts \
// 		--output-dir /home/runner/work/cal.diy/cal.diy/apps/web/playwright \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/cal.diy/cal.diy/apps/web/playwright/scenario_availability_schedule_create_default_hours.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:3000");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Cookie"] = process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const scheduleCreatePostRequestBody: string = `{
        "json": {
            "name": "Skyramp Default Hours Test"
        }
    }`;

    // Execute Request
    const scheduleCreatePostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/trpc/availability/schedule.create",
        method: "POST",
        body: scheduleCreatePostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(scheduleCreatePostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(scheduleCreatePostResponse, "result.data.json.schedule.name"), 'schedule.name').toBe("Skyramp Default Hours Test");
    expect(getValue(scheduleCreatePostResponse, "result.data.json.schedule.id"), 'schedule.id').toBeGreaterThan(0);

    const createdScheduleId = getValue(scheduleCreatePostResponse, "result.data.json.schedule.id");

    // Request Body
    const scheduleGetPostRequestBody: string = `{
        "json": {
            "scheduleId": ${createdScheduleId}
        }
    }`;

    // Execute Request
    const scheduleGetPostResponse = await client.sendRequest({
        url: URL_localhost,
        path: "/api/trpc/availability/schedule.get",
        method: "POST",
        body: scheduleGetPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(scheduleGetPostResponse.statusCode, 'status code').toBe(200);
    expect(getValue(scheduleGetPostResponse, "result.data.json.id"), 'id').toBe(createdScheduleId);
    expect(getValue(scheduleGetPostResponse, "result.data.json.name"), 'name').toBe("Skyramp Default Hours Test");
    expect(getValue(scheduleGetPostResponse, "result.data.json.workingHours").length, 'workingHours length').toBe(1);
    expect(getValue(scheduleGetPostResponse, "result.data.json.workingHours.0.days"), 'workingHours.0.days').toEqual([1, 2, 3, 4, 5]);
    expect(getValue(scheduleGetPostResponse, "result.data.json.workingHours.0.startTime"), 'workingHours.0.startTime').toBe(540);
    expect(getValue(scheduleGetPostResponse, "result.data.json.workingHours.0.endTime"), 'workingHours.0.endTime').toBe(1080);
    expect(getValue(scheduleGetPostResponse, "result.data.json.workingHours.1"), 'workingHours.1').toBeUndefined();
});
